id: https://example.org/pidinst-base
name: pidinst
imports:
  - linkml:types
prefixes:
  linkml: https://w3id.org/linkml/
  pidinst: https://example.org/pidinst-base/
default_prefix: pidinst
default_range: string

enums:
  DateType:
    permissible_values:
      Commissioned:
      DeCommissioned:
  
  RelatedIdentifierType:
    permissible_values:
      ARK:
      arXiv:
      bibcode:
      DOI:
      EAN13:
      EISSN:
      Handle:
      IGSN:
      ISBN:
      ISSN:
      ISTC:
      LISSN:
      PMID:
      PURL:
      RAiD:
      RRID:
      UPC:
      URL:
      URN:
      w3id:

  RelationType:
    permissible_values:
      IsDescribedBy:
      IsNewVersionOf:
      IsPreviousVersionOf:
      HasComponent:
      IsComponentOf:
      References:
      HasMetadata:
      WasUsedIn:
      IsIdenticalTo:
      IsAttachedTo:

slots:

classes:
  Instrument:
    #extra_slots:
    #  allowed: true
    attributes:
      identifier:
        range: Identifier
        required: true
      schemaVersion:
        required: true
      landingPage:
        required: true
      name:
        required: true
      owners:
        range: Owner
        multivalued: true
        required: true
      manufacturers:
        range: Manufacturer
        multivalued: true
        required: true
      model:
        range: Model
      description:
      instrumentTypes:
        range: InstrumentType
        multivalued: true
      measuredVariables:
        multivalued: true
      dates:
        range: Date
        multivalued: true
      relatedIdentifiers:
        range: RelatedIdentifier
        multivalued: true
      alternateIdentifiers:
        range: AlternateIdentifier
        multivalued: true

  Identifier:
    attributes:
      identifier:
        required: true
      identifierType:
        required: true

  Owner:
    attributes:
      ownerName:
        required: true
      ownerContact:
      ownerIdentifier:
        range: OwnerIdentifier

  OwnerIdentifier:
    attributes:
      ownerIdentifier:
        required: true
      ownerIdentifierType:
        required: true

  Manufacturer:
    attributes:
      manufacturerName:
        required: true
      manufacturerIdentifier:
        range: ManufacturerIdentifier

  ManufacturerIdentifier:
    attributes:
      manufacturerIdentifier:
        required: true
      manufacturerIdentifierType:
        required: true

  Model:
    attributes:
      modelName:
        required: true
      modelIdentifier:
        range: ModelIdentifier

  ModelIdentifier:
    attributes:
      modelIdentifier:
        required: true
      modelIdentifierType:
        required: true

  InstrumentType:
    attributes:
      instrumentTypeName:
        required: true
      instrumentTypeIdentifier:
        range: InstrumentTypeIdentifier

  InstrumentTypeIdentifier:
    attributes:
      instrumentTypeIdentifier:
        required: true
      instrumentTypeIdentifierType:
        required: true

  Date:
    attributes:
      theDate:
        range: date
        required: true
      dateType:
        range: DateType
        required: true

  RelatedIdentifier:
    attributes:
      relatedIdentifier:
        required: true
      relatedIdentifierType:
        range: RelatedIdentifierType
        required: true
      relationType:
        range: RelationType
        required: true
      relatedIdentifierName:

  AlternateIdentifier:
    attributes:
      alternateIdentifier:
        required: true
      alternateIdentifierType:
        required: true
      alternateIdentifierName:
